sudo: false
language: python
python:
- '3.5'
install:
- pip install pip pybuilder --upgrade
- pyb install_dependencies
script:
- pyb -X run_unit_tests
before_deploy:
  - pyb -X package
  - pwd
  - ls -la
  - cd $dir_dist
deploy:
  provider: pypi
  user: cfranke
  password:
    secure: dOSKlCMN/564LXhiVAfutmLog+NAsuFCdpdDb0NggRz9av4PrhEPgUxUt0xGwedepolTnalQ1DeUTgHLACw5Cu79lOTox16dF32vCT/68s5JDRUB9c1uc2uTMzUg8bKnHzZ/DxfA/d08F/xHBiTdGM0sjGvK6Decc2ZdUacc3N57X9KxN2pKhIaj0BpYsjqlu5ovUrN5SfNWRNI7VWQ9MilJlr1xkQdmJ13pdRyLAdJN8tsBFSB+Wbp6DESdLqcdu0HqA8LcvXEYZYR0pMBd+OKC9kJo9zUuQHyww5s5RCV9SXN6ajZe7sj8EImlgAAG/ivh9Gl0Sv4RTuugY/2qXo5lb4OucsOUvCMxsiHbe0Xv5rIjqgKEd9u98eOyIlsIzvwJeSaqi228wtxRJzeC66NJcctNDuN/JHSayPLBsnjdbL3vf6qNrAZJ2ataRK1jOKlMkSmmxkZgqNh/EmQIRIe3IWKWD5AAkLEgRuwChMMBR7AOULpI237VDc4LvE4ifYkrNcA5dOrKSPgNydcoVc/TQpwY2R7tfkj8l8Loi5Ap2UkeUR/EDqv0qR9+kbkWA7S1HCw54MjAJTJP3HjfIqVhB/pJ54xnBoQpezBLyLqsLTBGANz6jM9O4UsAC6wjV3GZmcN60i9TRCBPPoBp4oBOZWekBDc4kpRFW0Qjs6c=
  distributions: sdist
  skip_cleanup: true
  on:
    repo: franke1276/scan
    branch: master
    python: '3.5'
notifications:
  slack:
    on_success: always
    rooms:
      secure: PBugBgZPwCVO5JLgQUzSHOVng5onPqdKvjwiQNqGPg5+ZQEHpPN46LBFjmgP3hM3y0Mk5KMwieYMydsFxTAph5nWrLL1CkpLj3P4kjfQ9YGVCgDkDpYDICjCFB0VSZ4KWINwN3ZiUrEe+mLXPrnHkF42vFRTZdF3wxtfMdmp6vsN6ggVgOd+0J71zmXCQO687Ifxx7BfSxShVRUEz6Ms+Zwy4WlQ0LUjgKSt05El+nWDQ2qQJP2Rax5RPGuT7comppeYB4ybQMCR51IBMikUe4SIh/1LPup2ExRt6N6AhkTXcls7+bseyW177wWWJcfwHo8ShNbJtrlAG5wAtsNAGJU25REJyRxVd6PH+SIm4vOhjqP2dHlmgveHKNXqJQ52eSbUFcxGy3sPsE4vUTgBqpAl+NDfnx0LRjfkkc3uoYL6/jJZrBYBhOLa0Z0UklMwJAg9b5b0LnsvphuPbgxXCqzw7MQYCMEBvYm2ookshadNN5UKCM0Vn1S2TGYQL5/1J4B1jJBOm3gLRAs4/Xgu0GyZX1JFLAkgwz0GMI8ctTnbRbfhbJhKnmETt76fIPrirLlWnIiiycCFvHfcABFtnGupojklBnqH0itmImkaV5nN4Q8QpNaNnh82342n69oQhzDZpdxiiHaVKhrDwumCQBLjqRe4aYL6Mkf5OAXQgRo=
